spring:
  application:
    name: celr-srv-gateway

  cloud:
    gateway:
      routes:
        - id: listar-pedidos
          uri: http://localhost:8081
          predicates:
            - Path=/serp/pedidos/**
          filters:
            - name: UsuarioLogadoFilter
              args: {}

server:
  port: 8080

auth:
  service:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO